const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('markl', {
  openDialog: () => ipcRenderer.invoke('dialog:open'),
  openFolderDialog: () => ipcRenderer.invoke('dialog:open-folder'),
  refreshWorkspace: (rootPath) => ipcRenderer.invoke('workspace:refresh', rootPath),
  searchWorkspace: (options) => ipcRenderer.invoke('workspace:search', options),
  saveAsDialog: (options) => ipcRenderer.invoke('dialog:save-as', options),
  exportHtmlDialog: (options) => ipcRenderer.invoke('dialog:export-html', options),
  exportPdfDialog: (options) => ipcRenderer.invoke('dialog:export-pdf', options),
  exportPdf: (options) => ipcRenderer.invoke('export:pdf', options),

  writeFile: (options) => ipcRenderer.invoke('file:write', options),
  readFile: (options) => ipcRenderer.invoke('file:read', options),
  createFile: (options) => ipcRenderer.invoke('file:create', options),
  createFolder: (options) => ipcRenderer.invoke('file:mkdir', options),
  renamePath: (options) => ipcRenderer.invoke('file:rename', options),
  deletePath: (options) => ipcRenderer.invoke('file:delete', options),
  revealInFolder: (targetPath) => ipcRenderer.invoke('shell:reveal', targetPath),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  statPath: (targetPath) => ipcRenderer.invoke('path:stat', targetPath),
  showTreeMenu: (payload) => ipcRenderer.invoke('tree:context-menu', payload),
  formatCode: (options) => ipcRenderer.invoke('code:format', options),
  saveImage: (options) => ipcRenderer.invoke('image:save', options),
  listAssets: (options) => ipcRenderer.invoke('image:list-assets', options),
  deleteImages: (options) => ipcRenderer.invoke('image:delete-files', options),
  resolveImages: (options) => ipcRenderer.invoke('image:resolve', options),
  saveRevision: (options) => ipcRenderer.invoke('revision:save', options),
  listRevisions: (options) => ipcRenderer.invoke('revision:list', options),
  readRevision: (options) => ipcRenderer.invoke('revision:read', options),
  getLaunchContext: () => ipcRenderer.invoke('app:launch-context'),
  getVersion: () => ipcRenderer.invoke('app:version'),
  inlineHtmlImages: (options) => ipcRenderer.invoke('html:inline-images', options),
  printDocument: () => ipcRenderer.invoke('app:print'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  dismissUpdate: (version) => ipcRenderer.invoke('update:dismiss', version),
  resolveDocumentLink: (options) => ipcRenderer.invoke('path:resolve-doc', options),
  setWatch: (options) => ipcRenderer.invoke('watch:set', options),
  saveDraft: (payload) => ipcRenderer.invoke('draft:save', payload),
  readDraft: () => ipcRenderer.invoke('draft:read'),
  clearDraft: () => ipcRenderer.invoke('draft:clear'),

  setTitle: (title) => ipcRenderer.send('app:set-title', title),
  setAppearance: (payload) => ipcRenderer.send('appearance:set', payload),
  doClose: () => ipcRenderer.send('app:do-close'),
  tryClose: () => ipcRenderer.send('app:try-close'),
  reloadWindow: () => ipcRenderer.send('app:reload'),
  zoom: (dir) => ipcRenderer.send('app:zoom', dir),
  toggleFullScreen: () => ipcRenderer.send('app:fullscreen'),
  toggleDevTools: () => ipcRenderer.send('app:devtools'),

  on: (channel, callback) => {
    const allowed = [
      'file:opened',
      'menu:new',
      'menu:open',
      'menu:open-folder',
      'menu:save',
      'menu:save-as',
      'menu:export-html',
      'menu:export-pdf',
      'menu:print',
      'menu:new-template',
      'menu:revisions',
      'menu:typeset',
      'menu:insert-asset',
      'menu:clean-images',
      'menu:toggle-mode',
      'menu:toggle-sidebar',
      'menu:theme',
      'menu:font',
      'menu:font-size',
      'menu:format',
      'menu:find',
      'menu:replace',
      'menu:workspace-search',
      'menu:check-update',
      'menu:quick-open',
      'menu:about',
      'update:available',
      'fs:change',
      'app:before-close'
    ];
    if (allowed.includes(channel)) ipcRenderer.on(channel, (_event, ...args) => callback(...args));
  }
});
